rename point_types to point_xyzir
Fool-Stuck/wheel_stuck_ws pull request #128
Opened 2024-08-14 02:59 UTC by Bey9434

velodyne_cloud_separatorのpoint_types.hppをpoint_xyzir.hppにリネームする #114

2024-08-16 03:12 UTC, Autumn60 commented on src/perception/velodyne_cloud_separator/include/velodyne_cloud_separator/point_xyzir.hpp
> +#define VELODYNE_CLOUD_SEPARATOR__POINT_XYZIR_HPP_
インクルードガード名をPOINT_XYZIR_HPP_に変えてほしいです。（ディレクトリ構造と一致させるため）

2024-08-16 03:14 UTC, Autumn60 requested changes
指摘箇所について修正お願いします :man_bowing:

2024-08-18 15:00 UTC, Bey9434 commented
現時点で、インクルードガード名とディレクトリ構造は一致していると思います。

2024-08-18 15:01 UTC, Bey9434 commented on src/perception/velodyne_cloud_separator/include/velodyne_cloud_separator/point_xyzir.hpp
> +#define VELODYNE_CLOUD_SEPARATOR__POINT_XYZIR_HPP_
現時点で、インクルードガード名とディレクトリ構造は一致していると思います。

2024-08-18 15:12 UTC, Autumn60 approved these changes
honnmaya
LGTM

2024-08-18 15:30 UTC, merged