Pre-Commit Setup Instructions for Developers
Fool-Stuck/wheel_stuck_ws pull request #132
Opened 2024-09-02 17:00 UTC by Bey9434

#116 を行いました。
参考サイト　pre-commit Documentation, "https://pre-commit.com/#install"

2024-09-03 03:50 UTC, Autumn60 requested changes
指摘の箇所の修正お願いします。
（GitHub上でボタン押すだけで修正はいるはず）

+@ 
`pre-commit install` コマンドはこのリポジトリのルートディレクトリで実行する必要があるので、その旨を追記するか、ルートディレクトリに移動するステップを追加して下さい。

2024-09-03 03:50 UTC, Autumn60 commented on README.md
> +## 3.Pre-Commit Setup Instructions for Developers
```suggestion
## 3. Pre-Commit Setup Instructions for Developers
```

2024-09-03 03:50 UTC, Autumn60 commented on README.md
> +   install pre-commit
```suggestion
   pre-commit install
```

2024-09-03 06:56 UTC, Autumn60 approved these changes
LGTM :+1:

2024-10-06 14:27 UTC, RyodoTanaka approved these changes
ヨシ！

2024-10-06 14:27 UTC, merged