create LICENSE
Fool-Stuck/wheel_stuck_ws pull request #74
Opened 2024-07-24 15:45 UTC by Autumn60

2024-07-25 11:08 UTC, RyodoTanaka requested changes
修正よろしくお願いします！

2024-07-25 11:08 UTC, RyodoTanaka commented on LICENSE
> +   Copyright [yyyy] [name of copyright owner]
年、Copyrightホルダーが書かれてないですね…
年は2024
ホルダーは Fool Stuck
にしておきますかね？

2024-07-25 11:25 UTC, Autumn60 commented on LICENSE
> +   Copyright [yyyy] [name of copyright owner]
@RyodoTanaka 
Copyright 2024 Fool Stuck Engineersで追記しました

2024-07-26 11:50 UTC, RyodoTanaka approved these changes
ヨシ！

2024-07-26 11:50 UTC, merged